# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

require_relative 'controller_test_base'

class SimpleCalculatorControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def self.startup
    self.controller = @@api_client.simple_calculator
  end

  # Check if multiplication works
  def test_multiply()
    # Parameters for the API call
    options = {}
    options['operation'] = 'MULTIPLY'
    options['x'] = 4
    options['y'] = 5

    # Perform the API call through the SDK function
    result = self.class.controller.get_calculate(options)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test whether the captured response is as we expected
    assert_not_nil(result)
    assert_equal('20', @response_catcher.response.raw_body)
  end

end
