# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ApimaticCalculator
  class APIMATICCalculatorClient
    # Singleton access to simple_calculator controller
    # @return [SimpleCalculatorController] Returns the controller instance
    def simple_calculator
      SimpleCalculatorController.instance
    end

  end
end
