# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ApimaticCalculator
  class Configuration
    # The base Uri for API calls
    @base_uri = 'http://examples.apimatic.io/apps/calculator'

    # The attribute accessors for public properties
    class << self
      attr_accessor :base_uri
    end

  end
end
