# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ApimaticCalculator
  class OperationTypeEnum
    # Represents the sum operator
    # Represents the subtract operator
    # Represents the multiply operator
    # Represents the divide operator
    OPERATION_TYPE_ENUM = [SUM = 'SUM', SUBTRACT = 'SUBTRACT', MULTIPLY = 'MULTIPLY', DIVIDE = 'DIVIDE']
  end
end